media:
  input: public
  output: /
content:
  - name: posts
    label: Riportok
    type: collection
    path: src/content/blog
    view:
      fields: [title, draft, pubDatetime]
    fields:
      - { name: title, label: Cím, type: string, required: true }
      - { name: description, label: Leírás (meta description), type: string, required: true }
      - { name: author, label: Szerző, type: string, default: KAVICS }
      - { name: pubDatetime, label: Közzététel dátuma, type: date, options: { time: true }, required: true }
      - { name: modDatetime, label: Frissítés dátuma, type: date, options: { time: true } }
      - { name: slug, label: Slug (URL), type: string }
      - { name: featured, label: Kiemelt, type: boolean }
      - { name: draft, label: Vázlat, type: boolean }
      - { name: tags, label: Témák, type: string, list: true }
      - { name: ogImage, label: OG kép (megosztási kép URL), type: string }
      - { name: body, label: Szöveg, type: rich-text }
  - name: about
    label: Rólunk oldal
    type: file
    path: src/pages/about.md
    fields:
      - {
          name: layout,
          type: string,
          hidden: true,
          default: "../layouts/AboutLayout.astro",
        }
      - { name: title, label: Cím, type: string }
      - {
          name: body,
          label: Szöveg,
          type: rich-text,
          options: { input: public/assets, output: /assets },
        }
